os: linux
language: generic
sudo: required
services:
  - docker

before_install:
  - cd server
  - docker build -t whoami7/docker-ci-cd-node-server -f Dockerfile.dev .

install:
  - docker run whoami7/docker-ci-cd-node-server npm run test
