version: "3"
services:
  # SERVER
  node-app:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "3000:3000"

  # REDIS
  redis:
    image: redis

  # WEB-CLIENT
  web-app:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3001:3000"
